ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of RPVMSSM_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_363 = ', GC_363
      WRITE(*,2) 'GC_921 = ', GC_921
      WRITE(*,2) 'GC_922 = ', GC_922
      WRITE(*,2) 'GC_923 = ', GC_923
      WRITE(*,2) 'GC_924 = ', GC_924
      WRITE(*,2) 'GC_929 = ', GC_929
